# Generated by Django 4.2.13 on 2026-05-08 07:52

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=50, verbose_name='联系人姓名')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='联系人电话')),
                ('adult_count', models.PositiveIntegerField(default=0, verbose_name='大人人数')),
                ('child_count', models.PositiveIntegerField(default=0, verbose_name='小孩人数')),
                ('deposit_paid', models.BooleanField(default=False, verbose_name='订金是否已付')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='订金金额')),
                ('status', models.CharField(choices=[('new', '新建'), ('participants_entered', '已录入参加者'), ('completed', '已完成'), ('canceled', '已取消')], default='new', max_length=32, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('balance_paid', models.BooleanField(default=False, verbose_name='余款是否已付')),
                ('balance_due_date', models.DateField(blank=True, null=True, verbose_name='余款期限')),
                ('tour_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='tours.tourgroup', verbose_name='旅游团')),
            ],
            options={
                'verbose_name': '申请单',
                'verbose_name_plural': '申请单',
                'db_table': 'application',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='姓名')),
                ('id_card', models.CharField(max_length=30, verbose_name='证件号')),
                ('is_contact', models.BooleanField(default=False, verbose_name='是否联系人')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='applications.application', verbose_name='申请单')),
            ],
            options={
                'verbose_name': '参加者',
                'verbose_name_plural': '参加者',
                'db_table': 'participant',
                'ordering': ['application_id', '-is_contact', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(fields=('application', 'id_card'), name='uniq_application_id_card'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status', 'deposit_paid', 'balance_paid'], name='application_status_e3aeda_idx'),
        ),
    ]
