# Generated by Django 4.2.13 on 2026-05-08 08:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='balance_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='余款金额'),
        ),
        migrations.AddField(
            model_name='application',
            name='balance_paid_at',
            field=models.DateField(blank=True, null=True, verbose_name='余款支付日期'),
        ),
        migrations.AddField(
            model_name='application',
            name='balance_receipt_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='余款交款单号'),
        ),
        migrations.AddField(
            model_name='application',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='取消时间'),
        ),
        migrations.AddField(
            model_name='application',
            name='deposit_paid_at',
            field=models.DateField(blank=True, null=True, verbose_name='订金支付日期'),
        ),
        migrations.AddField(
            model_name='application',
            name='deposit_receipt_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='订金交款单号'),
        ),
        migrations.AddField(
            model_name='application',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='退款金额'),
        ),
    ]
