# Generated by Django 4.2.13 on 2026-05-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_balance_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='出生日期'),
        ),
        migrations.AddField(
            model_name='application',
            name='contact_address',
            field=models.CharField(blank=True, max_length=200, verbose_name='联系地址'),
        ),
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='application',
            name='emergency_contact_address',
            field=models.CharField(blank=True, max_length=200, verbose_name='紧急联系地址'),
        ),
        migrations.AddField(
            model_name='application',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='紧急联系人姓名'),
        ),
        migrations.AddField(
            model_name='application',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='紧急联系电话'),
        ),
        migrations.AddField(
            model_name='application',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, max_length=20, verbose_name='与本人关系'),
        ),
        migrations.AddField(
            model_name='application',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女'), ('other', '其他')], default='other', max_length=10, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='application',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='邮政编码'),
        ),
        migrations.AlterField(
            model_name='application',
            name='contact_name',
            field=models.CharField(max_length=50, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='application',
            name='contact_phone',
            field=models.CharField(max_length=20, verbose_name='电话号码'),
        ),
    ]
