# Generated by Django 4.2.13 on 2026-05-08 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='路线名称')),
                ('destination', models.CharField(max_length=100, verbose_name='目的地')),
                ('description', models.TextField(blank=True, verbose_name='路线说明')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='tours.route', verbose_name='上级路线')),
            ],
            options={
                'verbose_name': '路线',
                'verbose_name_plural': '路线',
                'db_table': 'route',
                'ordering': ['destination', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TourGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='团代码')),
                ('start_date', models.DateField(verbose_name='出发日期')),
                ('deadline', models.DateField(verbose_name='截止日期')),
                ('max_capacity', models.PositiveIntegerField(verbose_name='人数限额')),
                ('price_adult', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='大人价格')),
                ('price_child', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='小孩价格')),
                ('is_price_published', models.BooleanField(default=False, verbose_name='是否公开价格')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tour_groups', to='tours.route', verbose_name='路线')),
            ],
            options={
                'verbose_name': '旅游团',
                'verbose_name_plural': '旅游团',
                'db_table': 'tour_group',
                'ordering': ['-start_date', 'code'],
                'indexes': [models.Index(fields=['start_date', 'deadline'], name='tour_group_start_d_f92b5f_idx'), models.Index(fields=['is_price_published', 'is_deleted'], name='tour_group_is_pric_827ef8_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['destination', 'is_deleted'], name='route_destina_4d94de_idx'),
        ),
    ]
