# Generated by Django 4.2.13 on 2026-05-08 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price_adult', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='原成人价')),
                ('old_price_child', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='原儿童价')),
                ('new_price_adult', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='新成人价')),
                ('new_price_child', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='新儿童价')),
                ('is_rejected', models.BooleanField(default=False, verbose_name='是否被拒绝')),
                ('reason', models.TextField(blank=True, verbose_name='原因（如已公开价格）')),
                ('changed_by', models.CharField(blank=True, max_length=100, verbose_name='修改人')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '价格变更历史',
                'verbose_name_plural': '价格变更历史',
                'db_table': 'price_change_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_field', models.CharField(max_length=50, verbose_name='变更字段')),
                ('old_value', models.TextField(blank=True, verbose_name='原值')),
                ('new_value', models.TextField(blank=True, verbose_name='新值')),
                ('reason', models.TextField(blank=True, verbose_name='变更原因')),
                ('changed_by', models.CharField(max_length=100, verbose_name='变更人')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='变更时间')),
            ],
            options={
                'verbose_name': '路线变更历史',
                'verbose_name_plural': '路线变更历史',
                'db_table': 'route_change_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['-created_at', 'destination', 'name'], 'verbose_name': '路线', 'verbose_name_plural': '路线'},
        ),
        migrations.RemoveIndex(
            model_name='route',
            name='route_destina_4d94de_idx',
        ),
        migrations.RemoveField(
            model_name='route',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='route',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='tours.route', verbose_name='前一版本'),
        ),
        migrations.AddField(
            model_name='route',
            name='season',
            field=models.CharField(blank=True, max_length=20, verbose_name='季节（如：春季、夏季）'),
        ),
        migrations.AddField(
            model_name='route',
            name='status',
            field=models.CharField(choices=[('active', '活跃'), ('inactive', '不活跃'), ('canceled', '已取消')], default='active', max_length=20, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='route',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AddField(
            model_name='route',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='版本号'),
        ),
        migrations.AddField(
            model_name='tourgroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['destination', 'status'], name='route_destina_db6b1d_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['name', 'version'], name='route_name_db1574_idx'),
        ),
        migrations.AddField(
            model_name='routechangehistory',
            name='old_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tours.route', verbose_name='上一版本路线'),
        ),
        migrations.AddField(
            model_name='routechangehistory',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_histories', to='tours.route', verbose_name='路线'),
        ),
        migrations.AddField(
            model_name='pricechangehistory',
            name='tour_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_histories', to='tours.tourgroup', verbose_name='旅游团'),
        ),
    ]
